apiVersion: v1
kind: Namespace
metadata:
  name: dmz

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-creator-sa
  namespace: dmz

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole  # ClusterRole for cluster-wide access
metadata:
  name: pod-creator-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding # ClusterRoleBinding for cluster-wide binding
metadata:
  name: create-pods-cluster-binding
subjects:
- kind: ServiceAccount
  name: pod-creator-sa
  namespace: dmz
roleRef:
  kind: ClusterRole
  name: pod-creator-cluster-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-creator
  namespace: dmz
spec:
  containers:
  - name: pod-creator
    image: ubuntu
    command: ["sh", "-c", "while true; do sleep 3600; done"]
  serviceAccountName: pod-creator-sa
