apiVersion: v1
kind: Namespace
metadata:
  name: dmz

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-creator-sa
  namespace: dmz

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role  # Changed to Role
metadata:
  name: pod-creator-role
  namespace: dmz
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # Changed to RoleBinding
metadata:
  name: create-pods-binding
  namespace: dmz
subjects:
- kind: ServiceAccount
  name: pod-creator-sa
  namespace: dmz
roleRef:
  kind: Role
  name: pod-creator-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-creator
  namespace: dmz
spec:
  containers:
  - name: pod-creator
    image: ubuntu
    command: ["sh", "-c", "while true; do sleep 3600; done"]
  serviceAccountName: pod-creator-sa
